/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CounterForm.java
 *
 * Created on Mar 12, 2011, 4:34:09 PM
 */

package ar.com.educacionit.java.advanced.thread;

import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Instructor
 */
public class CounterForm extends javax.swing.JFrame {

    /** Creates new form CounterForm */
    public CounterForm() {
        initComponents();        
        hilo1 = new Counter(tfHilo1);
        hilo1.setSleep(true);
        hilo2 = new Counter(tfHilo2);
        hilo2.setSleep(true);
        hilo3 = new Counter(tfHilo3);
        hilo3.setSleep(true);
        hilo4 = new Counter(tfHilo4);
        hilo4.setSleep(true);
        cargarComboPrioridad(prioridadHilo1);
        cargarComboPrioridad(prioridadHilo2);
        cargarComboPrioridad(prioridadHilo3);
        cargarComboPrioridad(prioridadHilo4);

        tfHilo1.getDocument().addDocumentListener(new DocumentListener() {

                    public void changedUpdate(DocumentEvent e) {
                        verificarMaximo(tfHilo1, hilo1, hilo4, hilo3, hilo2);
                    }

                    public void removeUpdate(DocumentEvent e) {
                        verificarMaximo(tfHilo1, hilo1, hilo4, hilo3, hilo2);
                    }

                    public void insertUpdate(DocumentEvent e) {
                        verificarMaximo(tfHilo1, hilo1, hilo4, hilo3, hilo2);
                    }
                }
        );

        tfHilo2.getDocument().addDocumentListener(new DocumentListener() {

                    public void changedUpdate(DocumentEvent e) {
                        verificarMaximo(tfHilo2, hilo2, hilo1, hilo3, hilo4);
                    }

                    public void removeUpdate(DocumentEvent e) {
                        verificarMaximo(tfHilo2, hilo2, hilo1, hilo3, hilo4);
                    }

                    public void insertUpdate(DocumentEvent e) {
                        verificarMaximo(tfHilo2, hilo2, hilo1, hilo3, hilo4);
                    }
                }
        );

        tfHilo3.getDocument().addDocumentListener(new DocumentListener() {

                    public void changedUpdate(DocumentEvent e) {
                        verificarMaximo(tfHilo3, hilo3, hilo1, hilo2, hilo4);
                    }

                    public void removeUpdate(DocumentEvent e) {
                        verificarMaximo(tfHilo3, hilo3, hilo1, hilo2, hilo4);
                    }

                    public void insertUpdate(DocumentEvent e) {
                        verificarMaximo(tfHilo3, hilo3, hilo1, hilo2, hilo4);
                    }
                }
        );

        tfHilo4.getDocument().addDocumentListener(new DocumentListener() {

                    public void changedUpdate(DocumentEvent e) {
                        verificarMaximo(tfHilo4, hilo4, hilo1, hilo2, hilo3);
                    }

                    public void removeUpdate(DocumentEvent e) {
                        verificarMaximo(tfHilo4, hilo4, hilo1, hilo2, hilo3);
                    }

                    public void insertUpdate(DocumentEvent e) {
                        verificarMaximo(tfHilo4, hilo4, hilo1, hilo2, hilo3);
                    }
                }
        );

    }

    private void verificarMaximo(JTextField tf, Counter c, Counter c1, Counter c2, Counter c3) {
        if(c!=null && c.getI()>c1.getI() && c.getI()>c2.getI() && c.getI() > c3.getI()) {
            tf.setBackground(Color.red);
            if (!tfHilo1.equals(tf)) tfHilo1.setBackground(Color.WHITE);
            if (!tfHilo2.equals(tf)) tfHilo2.setBackground(Color.WHITE);
            if (!tfHilo3.equals(tf)) tfHilo3.setBackground(Color.WHITE);
            if (!tfHilo4.equals(tf)) tfHilo4.setBackground(Color.WHITE);
        }
        else tf.setBackground(Color.WHITE);
    }


    private void cargarComboPrioridad(JComboBox combo) {
        for (Integer i = 1; i <= 10; i++) {
            combo.addItem(i);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        suspendHilo3 = new javax.swing.JButton();
        suspendHilo2 = new javax.swing.JButton();
        sleepTimeHilo1 = new javax.swing.JTextField();
        pauseHilo2 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stopHilo3 = new javax.swing.JButton();
        suspendHilo4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfHilo2 = new javax.swing.JTextField();
        tfHilo3 = new javax.swing.JTextField();
        prioridadHilo3 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        prioridadHilo1 = new javax.swing.JComboBox();
        resumeHilo1 = new javax.swing.JButton();
        stopHilo2 = new javax.swing.JButton();
        resumeHilo3 = new javax.swing.JButton();
        prioridadHilo4 = new javax.swing.JComboBox();
        suspendHilo1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        resumeHilo2 = new javax.swing.JButton();
        stopHilo1 = new javax.swing.JButton();
        sleepTimeHilo2 = new javax.swing.JTextField();
        prioridadHilo2 = new javax.swing.JComboBox();
        tfHilo1 = new javax.swing.JTextField();
        tfHilo4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        stopHilo4 = new javax.swing.JButton();
        sleepTimeHilo4 = new javax.swing.JTextField();
        pauseHilo1 = new javax.swing.JCheckBox();
        pauseHilo3 = new javax.swing.JCheckBox();
        pauseHilo4 = new javax.swing.JCheckBox();
        sleepTimeHilo3 = new javax.swing.JTextField();
        resumeHilo4 = new javax.swing.JButton();
        startHilo1 = new javax.swing.JButton();
        startHilo2 = new javax.swing.JButton();
        startHilo3 = new javax.swing.JButton();
        startHilo4 = new javax.swing.JButton();
        waitHilo1 = new javax.swing.JButton();
        notifyHilo1 = new javax.swing.JButton();
        waitHilo2 = new javax.swing.JButton();
        notifyHilo2 = new javax.swing.JButton();
        waitHilo3 = new javax.swing.JButton();
        notifyHilo3 = new javax.swing.JButton();
        waitHilo4 = new javax.swing.JButton();
        notifyHilo4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Threads");

        suspendHilo3.setText("suspend");
        suspendHilo3.setEnabled(false);
        suspendHilo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspendHilo3ActionPerformed(evt);
            }
        });

        suspendHilo2.setText("suspend");
        suspendHilo2.setEnabled(false);
        suspendHilo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspendHilo2ActionPerformed(evt);
            }
        });

        sleepTimeHilo1.setText("100");
        sleepTimeHilo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepTimeHilo1ActionPerformed(evt);
            }
        });

        pauseHilo2.setSelected(true);
        pauseHilo2.setText("Pause");
        pauseHilo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseHilo2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Prioridad");

        jLabel3.setText("Prioridad");

        stopHilo3.setText("Stop");
        stopHilo3.setEnabled(false);
        stopHilo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopHilo3ActionPerformed(evt);
            }
        });

        suspendHilo4.setText("suspend");
        suspendHilo4.setEnabled(false);
        suspendHilo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspendHilo4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Thread 4");

        tfHilo2.setText(" ");

        tfHilo3.setText(" ");

        prioridadHilo3.setMaximumRowCount(10);
        prioridadHilo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prioridadHilo3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Thread 2");

        jLabel1.setText("Thread 1");

        prioridadHilo1.setMaximumRowCount(10);
        prioridadHilo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prioridadHilo1ActionPerformed(evt);
            }
        });

        resumeHilo1.setText("resume");
        resumeHilo1.setEnabled(false);
        resumeHilo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeHilo1ActionPerformed(evt);
            }
        });

        stopHilo2.setText("Stop");
        stopHilo2.setEnabled(false);
        stopHilo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopHilo2ActionPerformed(evt);
            }
        });

        resumeHilo3.setText("resume");
        resumeHilo3.setEnabled(false);
        resumeHilo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeHilo3ActionPerformed(evt);
            }
        });

        prioridadHilo4.setMaximumRowCount(10);
        prioridadHilo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prioridadHilo4ActionPerformed(evt);
            }
        });

        suspendHilo1.setText("suspend");
        suspendHilo1.setEnabled(false);
        suspendHilo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspendHilo1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Thread 3");

        jLabel5.setText("Prioridad");

        resumeHilo2.setText("resume");
        resumeHilo2.setEnabled(false);
        resumeHilo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeHilo2ActionPerformed(evt);
            }
        });

        stopHilo1.setText("Stop");
        stopHilo1.setEnabled(false);
        stopHilo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopHilo1ActionPerformed(evt);
            }
        });

        sleepTimeHilo2.setText("100");
        sleepTimeHilo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepTimeHilo2ActionPerformed(evt);
            }
        });

        prioridadHilo2.setMaximumRowCount(10);
        prioridadHilo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prioridadHilo2ActionPerformed(evt);
            }
        });

        tfHilo1.setText(" ");
        tfHilo1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tfHilo1InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        tfHilo1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfHilo1PropertyChange(evt);
            }
        });

        tfHilo4.setText(" ");

        jLabel4.setText("Prioridad");

        stopHilo4.setText("Stop");
        stopHilo4.setEnabled(false);
        stopHilo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopHilo4ActionPerformed(evt);
            }
        });

        sleepTimeHilo4.setText("100");
        sleepTimeHilo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepTimeHilo4ActionPerformed(evt);
            }
        });

        pauseHilo1.setSelected(true);
        pauseHilo1.setText("Pause");
        pauseHilo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseHilo1ActionPerformed(evt);
            }
        });

        pauseHilo3.setSelected(true);
        pauseHilo3.setText("Pause");
        pauseHilo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseHilo3ActionPerformed(evt);
            }
        });

        pauseHilo4.setSelected(true);
        pauseHilo4.setText("Pause");
        pauseHilo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseHilo4ActionPerformed(evt);
            }
        });

        sleepTimeHilo3.setText("100");
        sleepTimeHilo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepTimeHilo3ActionPerformed(evt);
            }
        });

        resumeHilo4.setText("resume");
        resumeHilo4.setEnabled(false);
        resumeHilo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeHilo4ActionPerformed(evt);
            }
        });

        startHilo1.setText("Start");
        startHilo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startHilo1ActionPerformed(evt);
            }
        });

        startHilo2.setText("Start");
        startHilo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startHilo2ActionPerformed(evt);
            }
        });

        startHilo3.setText("Start");
        startHilo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startHilo3ActionPerformed(evt);
            }
        });

        startHilo4.setText("Start");
        startHilo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startHilo4ActionPerformed(evt);
            }
        });

        waitHilo1.setText("wait");
        waitHilo1.setEnabled(false);
        waitHilo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitHilo1ActionPerformed(evt);
            }
        });

        notifyHilo1.setText("notify");
        notifyHilo1.setEnabled(false);
        notifyHilo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifyHilo1ActionPerformed(evt);
            }
        });

        waitHilo2.setText("wait");
        waitHilo2.setEnabled(false);
        waitHilo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitHilo2ActionPerformed(evt);
            }
        });

        notifyHilo2.setText("notify");
        notifyHilo2.setEnabled(false);
        notifyHilo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifyHilo2ActionPerformed(evt);
            }
        });

        waitHilo3.setText("wait");
        waitHilo3.setEnabled(false);
        waitHilo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitHilo3ActionPerformed(evt);
            }
        });

        notifyHilo3.setText("notify");
        notifyHilo3.setEnabled(false);
        notifyHilo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifyHilo3ActionPerformed(evt);
            }
        });

        waitHilo4.setText("wait");
        waitHilo4.setEnabled(false);
        waitHilo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitHilo4ActionPerformed(evt);
            }
        });

        notifyHilo4.setText("notify");
        notifyHilo4.setEnabled(false);
        notifyHilo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifyHilo4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(41, 41, 41)
                        .addComponent(tfHilo4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41)
                        .addComponent(tfHilo3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(tfHilo1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41)
                        .addComponent(tfHilo2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startHilo1)
                    .addComponent(startHilo2)
                    .addComponent(startHilo3)
                    .addComponent(startHilo4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stopHilo1)
                    .addComponent(stopHilo2)
                    .addComponent(stopHilo3)
                    .addComponent(stopHilo4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(waitHilo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notifyHilo1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(waitHilo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notifyHilo2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(waitHilo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notifyHilo3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(waitHilo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notifyHilo4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(suspendHilo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resumeHilo1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(suspendHilo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resumeHilo2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prioridadHilo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pauseHilo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sleepTimeHilo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prioridadHilo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pauseHilo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sleepTimeHilo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(suspendHilo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resumeHilo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prioridadHilo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pauseHilo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sleepTimeHilo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(suspendHilo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resumeHilo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prioridadHilo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pauseHilo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sleepTimeHilo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(suspendHilo1)
                    .addComponent(resumeHilo1)
                    .addComponent(tfHilo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(prioridadHilo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pauseHilo1)
                    .addComponent(sleepTimeHilo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startHilo1)
                    .addComponent(stopHilo1)
                    .addComponent(waitHilo1)
                    .addComponent(notifyHilo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(suspendHilo2)
                        .addComponent(resumeHilo2)
                        .addComponent(tfHilo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(prioridadHilo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(startHilo2)
                        .addComponent(stopHilo2)
                        .addComponent(waitHilo2)
                        .addComponent(notifyHilo2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pauseHilo2)
                        .addComponent(sleepTimeHilo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(suspendHilo3)
                        .addComponent(resumeHilo3)
                        .addComponent(tfHilo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(prioridadHilo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(startHilo3)
                        .addComponent(stopHilo3)
                        .addComponent(waitHilo3)
                        .addComponent(notifyHilo3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pauseHilo3)
                        .addComponent(sleepTimeHilo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(suspendHilo4)
                        .addComponent(resumeHilo4)
                        .addComponent(tfHilo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(prioridadHilo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(startHilo4)
                        .addComponent(stopHilo4)
                        .addComponent(waitHilo4)
                        .addComponent(notifyHilo4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pauseHilo4)
                        .addComponent(sleepTimeHilo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopHilo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopHilo1ActionPerformed
        hilo1.stop();
        startHilo1.setEnabled(false);
        resumeHilo1.setEnabled(false);
        suspendHilo1.setEnabled(false);
        stopHilo1.setEnabled(false);
    }//GEN-LAST:event_stopHilo1ActionPerformed

    private void suspendHilo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspendHilo1ActionPerformed
        hilo1.suspend();
        resumeHilo1.setEnabled(true);
        suspendHilo1.setEnabled(false);
        waitHilo1.setEnabled(false);
    }//GEN-LAST:event_suspendHilo1ActionPerformed

    private void resumeHilo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeHilo1ActionPerformed
        hilo1.resume();
        resumeHilo1.setEnabled(false);
        waitHilo1.setEnabled(true);
        suspendHilo1.setEnabled(true);
    }//GEN-LAST:event_resumeHilo1ActionPerformed

    private void resumeHilo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeHilo2ActionPerformed
        hilo2.resume();
        resumeHilo2.setEnabled(false);
        suspendHilo2.setEnabled(true);
    }//GEN-LAST:event_resumeHilo2ActionPerformed

    private void suspendHilo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspendHilo2ActionPerformed
        hilo2.suspend();
        resumeHilo2.setEnabled(true);
        suspendHilo2.setEnabled(false);
    }//GEN-LAST:event_suspendHilo2ActionPerformed

    private void stopHilo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopHilo2ActionPerformed
        hilo2.stop();
        startHilo2.setEnabled(false);
        resumeHilo2.setEnabled(false);
        suspendHilo2.setEnabled(false);
        stopHilo2.setEnabled(false);
    }//GEN-LAST:event_stopHilo2ActionPerformed

    private void prioridadHilo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prioridadHilo1ActionPerformed
        hilo1.setPriority((Integer)prioridadHilo1.getSelectedItem());
    }//GEN-LAST:event_prioridadHilo1ActionPerformed

    private void prioridadHilo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prioridadHilo2ActionPerformed
        hilo2.setPriority((Integer)prioridadHilo2.getSelectedItem());
    }//GEN-LAST:event_prioridadHilo2ActionPerformed

    private void pauseHilo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseHilo1ActionPerformed
        hilo1.setSleep(pauseHilo1.isSelected());
    }//GEN-LAST:event_pauseHilo1ActionPerformed

    private void pauseHilo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseHilo2ActionPerformed
        hilo2.setSleep(pauseHilo2.isSelected());
    }//GEN-LAST:event_pauseHilo2ActionPerformed

    private void sleepTimeHilo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepTimeHilo1ActionPerformed
        hilo1.setSleepTime(new Integer(sleepTimeHilo1.getText()));
    }//GEN-LAST:event_sleepTimeHilo1ActionPerformed

    private void sleepTimeHilo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepTimeHilo2ActionPerformed
        hilo2.setSleepTime(new Integer(sleepTimeHilo2.getText()));
    }//GEN-LAST:event_sleepTimeHilo2ActionPerformed

    private void pauseHilo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseHilo3ActionPerformed
        hilo3.setSleep(pauseHilo3.isSelected());
    }//GEN-LAST:event_pauseHilo3ActionPerformed

    private void prioridadHilo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prioridadHilo3ActionPerformed
        hilo3.setPriority((Integer)prioridadHilo3.getSelectedItem());
    }//GEN-LAST:event_prioridadHilo3ActionPerformed

    private void sleepTimeHilo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepTimeHilo3ActionPerformed
        hilo3.setSleepTime(new Integer(sleepTimeHilo3.getText()));
    }//GEN-LAST:event_sleepTimeHilo3ActionPerformed

    private void stopHilo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopHilo3ActionPerformed
        hilo3.stop();
        startHilo3.setEnabled(false);
        resumeHilo3.setEnabled(false);
        suspendHilo3.setEnabled(false);
        stopHilo3.setEnabled(false);
    }//GEN-LAST:event_stopHilo3ActionPerformed

    private void suspendHilo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspendHilo3ActionPerformed
        hilo3.suspend();
        resumeHilo3.setEnabled(true);
        suspendHilo3.setEnabled(false);
    }//GEN-LAST:event_suspendHilo3ActionPerformed

    private void resumeHilo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeHilo3ActionPerformed
        hilo3.resume();
        resumeHilo3.setEnabled(false);
        suspendHilo3.setEnabled(true);
    }//GEN-LAST:event_resumeHilo3ActionPerformed

    private void pauseHilo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseHilo4ActionPerformed
        hilo4.setSleep(pauseHilo4.isSelected());
    }//GEN-LAST:event_pauseHilo4ActionPerformed

    private void prioridadHilo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prioridadHilo4ActionPerformed
        hilo4.setPriority((Integer)prioridadHilo4.getSelectedItem());
    }//GEN-LAST:event_prioridadHilo4ActionPerformed

    private void sleepTimeHilo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepTimeHilo4ActionPerformed
        hilo4.setSleepTime(new Integer(sleepTimeHilo4.getText()));
    }//GEN-LAST:event_sleepTimeHilo4ActionPerformed

    private void stopHilo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopHilo4ActionPerformed
        hilo4.stop();
        startHilo4.setEnabled(false);
        resumeHilo4.setEnabled(false);
        suspendHilo4.setEnabled(false);
        stopHilo4.setEnabled(false);
    }//GEN-LAST:event_stopHilo4ActionPerformed

    private void suspendHilo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspendHilo4ActionPerformed
        hilo4.suspend();
        resumeHilo4.setEnabled(true);
        suspendHilo4.setEnabled(false);
    }//GEN-LAST:event_suspendHilo4ActionPerformed

    private void resumeHilo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeHilo4ActionPerformed
        hilo4.resume();
        resumeHilo4.setEnabled(false);
        suspendHilo4.setEnabled(true);
    }//GEN-LAST:event_resumeHilo4ActionPerformed

    private void tfHilo1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfHilo1PropertyChange
        
    }//GEN-LAST:event_tfHilo1PropertyChange

    private void tfHilo1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tfHilo1InputMethodTextChanged
        
    }//GEN-LAST:event_tfHilo1InputMethodTextChanged

    private void startHilo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startHilo1ActionPerformed
        prioridadHilo1ActionPerformed(evt);
        sleepTimeHilo1ActionPerformed(evt);
        hilo1.start();
        startHilo1.setEnabled(false);
        suspendHilo1.setEnabled(true);
        stopHilo1.setEnabled(true);
        waitHilo1.setEnabled(true);
    }//GEN-LAST:event_startHilo1ActionPerformed

    private void startHilo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startHilo2ActionPerformed
        prioridadHilo2ActionPerformed(evt);
        sleepTimeHilo2ActionPerformed(evt);
        startHilo2.setEnabled(false);
        suspendHilo2.setEnabled(true);
        stopHilo2.setEnabled(true);
        hilo2.start();
        waitHilo2.setEnabled(true);
    }//GEN-LAST:event_startHilo2ActionPerformed

    private void startHilo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startHilo3ActionPerformed
        prioridadHilo3ActionPerformed(evt);
        sleepTimeHilo3ActionPerformed(evt);
        hilo3.start();
        startHilo3.setEnabled(false);
        suspendHilo3.setEnabled(true);
        stopHilo3.setEnabled(true);
        waitHilo3.setEnabled(true);
    }//GEN-LAST:event_startHilo3ActionPerformed

    private void startHilo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startHilo4ActionPerformed
        prioridadHilo4ActionPerformed(evt);
        sleepTimeHilo4ActionPerformed(evt);
        hilo4.start();
        startHilo4.setEnabled(false);
        suspendHilo4.setEnabled(true);
        stopHilo4.setEnabled(true);
        waitHilo4.setEnabled(true);
    }//GEN-LAST:event_startHilo4ActionPerformed

    private void waitHilo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitHilo1ActionPerformed
        hilo1.suspender();
        waitHilo1.setEnabled(false);
        suspendHilo1.setEnabled(false);
        notifyHilo1.setEnabled(true);        
    }//GEN-LAST:event_waitHilo1ActionPerformed

    private void notifyHilo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifyHilo1ActionPerformed
        hilo1.reanudad();
        waitHilo1.setEnabled(true);
        suspendHilo1.setEnabled(true);
        notifyHilo1.setEnabled(false);

    }//GEN-LAST:event_notifyHilo1ActionPerformed

    private void waitHilo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitHilo2ActionPerformed
        hilo2.suspender();
        waitHilo2.setEnabled(false);
        notifyHilo2.setEnabled(true);
    }//GEN-LAST:event_waitHilo2ActionPerformed

    private void notifyHilo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifyHilo2ActionPerformed
        hilo2.reanudad();
        waitHilo2.setEnabled(true);
        notifyHilo2.setEnabled(false);
    }//GEN-LAST:event_notifyHilo2ActionPerformed

    private void waitHilo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitHilo3ActionPerformed
        hilo3.suspender();
        waitHilo3.setEnabled(false);
        notifyHilo3.setEnabled(true);
    }//GEN-LAST:event_waitHilo3ActionPerformed

    private void notifyHilo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifyHilo3ActionPerformed
        hilo3.reanudad();
        waitHilo3.setEnabled(true);
        notifyHilo3.setEnabled(false);
    }//GEN-LAST:event_notifyHilo3ActionPerformed

    private void waitHilo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitHilo4ActionPerformed
        hilo4.suspender();
        waitHilo4.setEnabled(false);
        notifyHilo4.setEnabled(true);
    }//GEN-LAST:event_waitHilo4ActionPerformed

    private void notifyHilo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifyHilo4ActionPerformed
        hilo4.reanudad();
        waitHilo4.setEnabled(true);
        notifyHilo4.setEnabled(false);
    }//GEN-LAST:event_notifyHilo4ActionPerformed
   
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CounterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton notifyHilo1;
    private javax.swing.JButton notifyHilo2;
    private javax.swing.JButton notifyHilo3;
    private javax.swing.JButton notifyHilo4;
    private javax.swing.JCheckBox pauseHilo1;
    private javax.swing.JCheckBox pauseHilo2;
    private javax.swing.JCheckBox pauseHilo3;
    private javax.swing.JCheckBox pauseHilo4;
    private javax.swing.JComboBox prioridadHilo1;
    private javax.swing.JComboBox prioridadHilo2;
    private javax.swing.JComboBox prioridadHilo3;
    private javax.swing.JComboBox prioridadHilo4;
    private javax.swing.JButton resumeHilo1;
    private javax.swing.JButton resumeHilo2;
    private javax.swing.JButton resumeHilo3;
    private javax.swing.JButton resumeHilo4;
    private javax.swing.JTextField sleepTimeHilo1;
    private javax.swing.JTextField sleepTimeHilo2;
    private javax.swing.JTextField sleepTimeHilo3;
    private javax.swing.JTextField sleepTimeHilo4;
    private javax.swing.JButton startHilo1;
    private javax.swing.JButton startHilo2;
    private javax.swing.JButton startHilo3;
    private javax.swing.JButton startHilo4;
    private javax.swing.JButton stopHilo1;
    private javax.swing.JButton stopHilo2;
    private javax.swing.JButton stopHilo3;
    private javax.swing.JButton stopHilo4;
    private javax.swing.JButton suspendHilo1;
    private javax.swing.JButton suspendHilo2;
    private javax.swing.JButton suspendHilo3;
    private javax.swing.JButton suspendHilo4;
    private javax.swing.JTextField tfHilo1;
    private javax.swing.JTextField tfHilo2;
    private javax.swing.JTextField tfHilo3;
    private javax.swing.JTextField tfHilo4;
    private javax.swing.JButton waitHilo1;
    private javax.swing.JButton waitHilo2;
    private javax.swing.JButton waitHilo3;
    private javax.swing.JButton waitHilo4;
    // End of variables declaration//GEN-END:variables

    private Counter hilo1;
    private Counter hilo2;
    private Counter hilo3;
    private Counter hilo4;
}
